<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        $questions = [
            ['number' => 1, 'text' => 'My manager sets a clear vision for my team.', 'dimensions' => json_encode(["Leadership & Management","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 2, 'text' => 'Leaders communicate openly and transparently.', 'dimensions' => json_encode(["Leadership & Management","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 3, 'text' => 'I trust my leadership team’s decisions.', 'dimensions' => json_encode(["Leadership & Management","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 4, 'text' => 'My manager encourages innovation and new ideas.', 'dimensions' => json_encode(["Leadership & Management","Innovation & Agility"]), 'reverse_coded' => false],
            ['number' => 5, 'text' => 'Senior leaders demonstrate ethical behavior.', 'dimensions' => json_encode(["Leadership & Management","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 6, 'text' => 'Leadership makes me feel valued as an employee.', 'dimensions' => json_encode(["Leadership & Management","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 7, 'text' => 'Leaders actively listen to employee feedback.', 'dimensions' => json_encode(["Leadership & Management","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 8, 'text' => 'My manager resolves conflicts fairly.', 'dimensions' => json_encode(["Leadership & Management","Teamwork & Collaboration"]), 'reverse_coded' => false],
            ['number' => 9, 'text' => 'I feel confident about the company’s strategic direction.', 'dimensions' => json_encode(["Strategic Alignment","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 10, 'text' => 'My leadership recognizes and celebrates achievements.', 'dimensions' => json_encode(["Leadership & Management","Career Progression & Recognition"]), 'reverse_coded' => false],
            ['number' => 11, 'text' => 'I have the skills needed to do my job effectively.', 'dimensions' => json_encode(["Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 12, 'text' => 'I receive adequate training to enhance my skills.', 'dimensions' => json_encode(["Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 13, 'text' => 'My team members are competent in their roles.', 'dimensions' => json_encode(["Teamwork & Collaboration","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 14, 'text' => 'I am encouraged to learn new technologies/tools.', 'dimensions' => json_encode(["Capability & Skill Development","Innovation & Agility"]), 'reverse_coded' => false],
            ['number' => 15, 'text' => 'My manager supports upskilling and certification.', 'dimensions' => json_encode(["Leadership & Management","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 16, 'text' => 'I feel confident handling unexpected challenges.', 'dimensions' => json_encode(["Capability & Skill Development","Innovation & Agility"]), 'reverse_coded' => false],
            ['number' => 17, 'text' => 'Cross-functional teams work with high proficiency.', 'dimensions' => json_encode(["Teamwork & Collaboration","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 18, 'text' => 'My technical knowledge is respected within the organization.', 'dimensions' => json_encode(["Capability & Skill Development","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 19, 'text' => 'I receive constructive feedback to improve performance.', 'dimensions' => json_encode(["Leadership & Management","Career Progression & Recognition"]), 'reverse_coded' => false],
            ['number' => 20, 'text' => 'I am empowered to make decisions within my role.', 'dimensions' => json_encode(["Leadership & Management","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 21, 'text' => 'The company adapts quickly to industry changes.', 'dimensions' => json_encode(["Innovation & Agility","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 22, 'text' => 'New ideas are welcomed and tested.', 'dimensions' => json_encode(["Innovation & Agility","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 23, 'text' => 'I am encouraged to experiment without fear of failure.', 'dimensions' => json_encode(["Innovation & Agility","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 24, 'text' => 'Our processes are efficient and adaptable.', 'dimensions' => json_encode(["Innovation & Agility","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 25, 'text' => 'We quickly respond to customer and market needs.', 'dimensions' => json_encode(["Innovation & Agility","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 26, 'text' => 'Digital transformation is effectively implemented.', 'dimensions' => json_encode(["Innovation & Agility","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 27, 'text' => 'My team proactively solves emerging challenges.', 'dimensions' => json_encode(["Innovation & Agility","Teamwork & Collaboration"]), 'reverse_coded' => false],
            ['number' => 28, 'text' => 'Innovation is recognized and rewarded here.', 'dimensions' => json_encode(["Innovation & Agility","Career Progression & Recognition"]), 'reverse_coded' => false],
            ['number' => 29, 'text' => 'I feel safe suggesting unconventional solutions.', 'dimensions' => json_encode(["Innovation & Agility","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 30, 'text' => 'The company invests in research and technology.', 'dimensions' => json_encode(["Innovation & Agility","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 31, 'text' => 'The organization’s mission is clear to me.', 'dimensions' => json_encode(["Strategic Alignment","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 32, 'text' => 'I understand how my role contributes to company goals.', 'dimensions' => json_encode(["Strategic Alignment","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 33, 'text' => 'Leadership effectively communicates future plans.', 'dimensions' => json_encode(["Leadership & Management","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 34, 'text' => 'I believe in the company’s long-term growth strategy.', 'dimensions' => json_encode(["Strategic Alignment","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 35, 'text' => 'I understand the company’s competitive positioning.', 'dimensions' => json_encode(["Strategic Alignment","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 36, 'text' => 'Strategic priorities are aligned across departments.', 'dimensions' => json_encode(["Strategic Alignment","Teamwork & Collaboration"]), 'reverse_coded' => false],
            ['number' => 37, 'text' => 'I receive updates on business performance regularly.', 'dimensions' => json_encode(["Strategic Alignment","Leadership & Management"]), 'reverse_coded' => false],
            ['number' => 38, 'text' => 'I feel motivated by the company’s future direction.', 'dimensions' => json_encode(["Strategic Alignment","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 39, 'text' => 'Management decisions are aligned with stated values.', 'dimensions' => json_encode(["Leadership & Management","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 40, 'text' => 'I understand how success is measured at Summit.', 'dimensions' => json_encode(["Strategic Alignment","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 41, 'text' => 'My team members support each other.', 'dimensions' => json_encode(["Teamwork & Collaboration","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 42, 'text' => 'Departments collaborate effectively.', 'dimensions' => json_encode(["Teamwork & Collaboration","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 43, 'text' => 'Knowledge sharing is encouraged.', 'dimensions' => json_encode(["Teamwork & Collaboration","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 44, 'text' => 'I feel comfortable reaching out for help from colleagues.', 'dimensions' => json_encode(["Teamwork & Collaboration","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 45, 'text' => 'My contributions are valued by my team.', 'dimensions' => json_encode(["Teamwork & Collaboration","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 46, 'text' => 'We resolve conflicts constructively.', 'dimensions' => json_encode(["Teamwork & Collaboration","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 47, 'text' => 'My team trusts each other’s judgment.', 'dimensions' => json_encode(["Teamwork & Collaboration","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 48, 'text' => 'There are no silos hindering teamwork.', 'dimensions' => json_encode(["Teamwork & Collaboration","Strategic Alignment"]), 'reverse_coded' => true],
            ['number' => 49, 'text' => 'Cross-functional collaboration is smooth.', 'dimensions' => json_encode(["Teamwork & Collaboration","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 50, 'text' => 'I am proud to work with my colleagues.', 'dimensions' => json_encode(["Teamwork & Collaboration","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 51, 'text' => 'I feel respected regardless of my background.', 'dimensions' => json_encode(["Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 52, 'text' => 'Diversity and inclusion are valued here.', 'dimensions' => json_encode(["Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 53, 'text' => 'I have a healthy work-life balance.', 'dimensions' => json_encode(["Culture & Wellbeing","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 54, 'text' => 'The organization prioritizes employee well-being.', 'dimensions' => json_encode(["Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 55, 'text' => 'Workplace policies are fair and transparent.', 'dimensions' => json_encode(["Culture & Wellbeing","Leadership & Management"]), 'reverse_coded' => false],
            ['number' => 56, 'text' => 'I feel psychologically safe at work.', 'dimensions' => json_encode(["Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 57, 'text' => 'Employees are treated equitably across levels.', 'dimensions' => json_encode(["Culture & Wellbeing","Leadership & Management"]), 'reverse_coded' => false],
            ['number' => 58, 'text' => 'The office environment promotes productivity.', 'dimensions' => json_encode(["Culture & Wellbeing","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 59, 'text' => 'I am satisfied with workplace facilities.', 'dimensions' => json_encode(["Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 60, 'text' => 'Summit fosters a positive, respectful culture.', 'dimensions' => json_encode(["Culture & Wellbeing","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 61, 'text' => 'There are sufficient opportunities for personal growth.', 'dimensions' => json_encode(["Career Progression & Recognition","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 62, 'text' => 'I am encouraged to take ownership of my development.', 'dimensions' => json_encode(["Career Progression & Recognition","Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 63, 'text' => 'Learning resources are easily accessible.', 'dimensions' => json_encode(["Capability & Skill Development"]), 'reverse_coded' => false],
            ['number' => 64, 'text' => 'My career goals are supported by management.', 'dimensions' => json_encode(["Career Progression & Recognition","Leadership & Management"]), 'reverse_coded' => false],
            ['number' => 65, 'text' => 'I am given time for self-learning.', 'dimensions' => json_encode(["Capability & Skill Development","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 66, 'text' => 'I receive mentorship or coaching when needed.', 'dimensions' => json_encode(["Leadership & Management","Career Progression & Recognition"]), 'reverse_coded' => false],
            ['number' => 67, 'text' => 'I have access to relevant workshops and certifications.', 'dimensions' => json_encode(["Capability & Skill Development","Career Progression & Recognition"]), 'reverse_coded' => false],
            ['number' => 68, 'text' => 'I feel confident about acquiring new competencies.', 'dimensions' => json_encode(["Capability & Skill Development","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 69, 'text' => 'My manager regularly discusses my development plan.', 'dimensions' => json_encode(["Leadership & Management","Career Progression & Recognition"]), 'reverse_coded' => false],
            ['number' => 70, 'text' => 'Summit invests in employees’ lifelong learning.', 'dimensions' => json_encode(["Capability & Skill Development","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 71, 'text' => 'I understand the promotion criteria at Summit.', 'dimensions' => json_encode(["Career Progression & Recognition","Leadership & Management"]), 'reverse_coded' => false],
            ['number' => 72, 'text' => 'I see a clear career path within the company.', 'dimensions' => json_encode(["Career Progression & Recognition","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 73, 'text' => 'Internal opportunities are communicated transparently.', 'dimensions' => json_encode(["Career Progression & Recognition","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 74, 'text' => 'My manager discusses career aspirations with me.', 'dimensions' => json_encode(["Leadership & Management","Career Progression & Recognition"]), 'reverse_coded' => false],
            ['number' => 75, 'text' => 'High performers are recognized and rewarded.', 'dimensions' => json_encode(["Career Progression & Recognition","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 76, 'text' => 'The performance review process is fair.', 'dimensions' => json_encode(["Career Progression & Recognition","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 77, 'text' => 'I feel supported in achieving my career goals.', 'dimensions' => json_encode(["Career Progression & Recognition","Leadership & Management"]), 'reverse_coded' => false],
            ['number' => 78, 'text' => 'I trust the promotion decisions made here.', 'dimensions' => json_encode(["Career Progression & Recognition","Leadership & Management"]), 'reverse_coded' => false],
            ['number' => 79, 'text' => 'My contributions impact my career growth.', 'dimensions' => json_encode(["Career Progression & Recognition","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 80, 'text' => 'Summit provides equal opportunities for advancement.', 'dimensions' => json_encode(["Career Progression & Recognition","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 81, 'text' => 'I feel proud to work at Summit.', 'dimensions' => json_encode(["Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 82, 'text' => 'My compensation is competitive.', 'dimensions' => json_encode(["Career Progression & Recognition"]), 'reverse_coded' => false],
            ['number' => 83, 'text' => 'Benefits offered meet my needs.', 'dimensions' => json_encode(["Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 84, 'text' => 'My work gives me a sense of purpose.', 'dimensions' => json_encode(["Engagement & Commitment","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 85, 'text' => 'I feel valued for my contributions.', 'dimensions' => json_encode(["Engagement & Commitment","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 86, 'text' => 'I have a good relationship with my manager.', 'dimensions' => json_encode(["Leadership & Management","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 87, 'text' => 'I would recommend Summit as a great place to work.', 'dimensions' => json_encode(["Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 88, 'text' => 'I feel motivated to perform my best here.', 'dimensions' => json_encode(["Engagement & Commitment","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 89, 'text' => 'I see myself working here for the next 2 years.', 'dimensions' => json_encode(["Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 90, 'text' => 'My work-life balance influences my decision to stay.', 'dimensions' => json_encode(["Culture & Wellbeing","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 91, 'text' => 'I regularly consider leaving the organization.', 'dimensions' => json_encode(["Engagement & Commitment","Attrition Risk"]), 'reverse_coded' => true],
            ['number' => 92, 'text' => 'I feel there are better opportunities elsewhere.', 'dimensions' => json_encode(["Attrition Risk","Career Progression & Recognition"]), 'reverse_coded' => true],
            ['number' => 93, 'text' => 'I am satisfied with my job role and responsibilities.', 'dimensions' => json_encode(["Engagement & Commitment","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 94, 'text' => 'I feel aligned with the company’s long-term vision.', 'dimensions' => json_encode(["Engagement & Commitment","Strategic Alignment"]), 'reverse_coded' => false],
            ['number' => 95, 'text' => 'I believe leadership values retaining employees.', 'dimensions' => json_encode(["Leadership & Management","Attrition Risk"]), 'reverse_coded' => false],
            ['number' => 96, 'text' => 'I feel secure about my job future here.', 'dimensions' => json_encode(["Attrition Risk","Culture & Wellbeing"]), 'reverse_coded' => false],
            ['number' => 97, 'text' => 'My growth here outweighs opportunities elsewhere.', 'dimensions' => json_encode(["Attrition Risk","Career Progression & Recognition"]), 'reverse_coded' => false],
            ['number' => 98, 'text' => 'I am satisfied with recognition and rewards.', 'dimensions' => json_encode(["Career Progression & Recognition","Engagement & Commitment"]), 'reverse_coded' => false],
            ['number' => 99, 'text' => 'I rarely experience burnout or stress at work.', 'dimensions' => json_encode(["Culture & Wellbeing","Attrition Risk"]), 'reverse_coded' => true],
            ['number' => 100, 'text' => 'I see Summit as a place where I can grow long-term.', 'dimensions' => json_encode(["Career Progression & Recognition","Engagement & Commitment"]), 'reverse_coded' => false],
        ];

        foreach ($questions as $q) {
            DB::table('questions')->insert([
                'number' => $q['number'],
                'text' => $q['text'],
                'dimension' => $q['dimensions'],
                'reverse_coded' => $q['reverse_coded'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('✅ 100 Employee Engagement Survey questions seeded successfully!');
    }
}
